rm(list = ls())
cnf = yaml::read_yaml('config.yml')
sapply(list.files('code', recursive = T, full.names = T), source)
# tidy(list.files('data/raw', full.names = T), cnf)
df = preprocess(cnf)
l = list()
l[['actitudes']] <- create_section_actitudes(df)
l[['cognitivas']] <- create_section_cognitivas(df)
